### ISSUE TITLE
(MSU-MD) Road Rash 3 patch

### ISSUE THREAD

**Issue by odiaboeeu** [ArcadeTV/msuplus-tracker#5]
You could make road rash 3 using the ost redone by Dean Harris?

https://www.youtube.com/@DeanHarrisComposer/videos

If you need the ost made by him I send you link with the music files.

Thanks for your work :)

**Comment by ArcadeTV** [comment]
The sound driver by Don Veca is similar to GEMS, but without any documentation or disassembly I'm afraid it's not doable for me. Since Mr. Veca seems to be still working, you could just ask him if he would be willing to provide docs or sources for his driver.

https://www.linkedin.com/in/don-veca-32b92414

**Comment by ArcadeTV** [comment]
It seems there already is an improvement patch that adds CD audio:
https://www.zeldix.net/t2579-road-rash-3-md
